version: '3'
services:

  db:
    image: "mysql:5.7"
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: movie

  movie:
    depends_on:
      - db
    image: "yunyizhiying/movie"
    ports:
      - "8000:8000"
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_HOST: db:3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      DATABASE_NAME: movie
      LISTEN_ADDR: :8000

volumes:
  mysql_data:
